# Generated by Django 4.1.1 on 2022-10-10 23:46

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=home.models.BlogPost.pub_date_default, verbose_name='date published')),
                ('title', models.CharField(default=home.models.BlogPost.title_default, max_length=200)),
                ('body', models.CharField(default=home.models.BlogPost.body_default, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/images/')),
            ],
        ),
    ]
