# Generated by Django 4.1.1 on 2022-10-04 18:24

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_arb_arbitrary_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=home.models.BlogPost.title_default, max_length=200)),
                ('body', models.CharField(default=home.models.BlogPost.body_default, max_length=1500)),
            ],
        ),
        migrations.DeleteModel(
            name='Arbitrary',
        ),
    ]
