# Generated by Django 4.1.1 on 2022-10-08 20:14

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blogpost_delete_arbitrary'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateTimeField(default=home.models.BlogPost.pub_date_default, verbose_name='date published'),
        ),
    ]
